// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("PeakSimulator")>]
[<assembly: AssemblyProductAttribute("PeakSimulator")>]
[<assembly: AssemblyDescriptionAttribute("A short randomized simulator for peaks/whole chromatograms.")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "PeakSimulator"
    let [<Literal>] AssemblyProduct = "PeakSimulator"
    let [<Literal>] AssemblyDescription = "A short randomized simulator for peaks/whole chromatograms."
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
